##################
###Window Rules###
##################

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = float, xwayland,fullscreen:0,pinned:0

# Obsidian fullscreen on workspace 14
windowrulev2 = workspace 14 silent, fullscreen, class:obsidian

# VS Code 
windowrulev2 = workspace 6 silent, class:code

# Firefox 
windowrulev2 = workspace 1, class:firefox
# terminal
windowrulev2 = workspace 2, class:AlacrittyFirst
# Outlook & Teams
windowrulev2 = workspace 20 silent, tag:msg
# Pulse VPN
windowrulev2 = workspace special:magic silent, float, initialClass:pulseUI
windowrulev2 = float, initialClass:pulseUI
windowrulev2 = size 600 400, float, initialClass:pulseUI
# XWayland Bridge 
windowrulev2 = workspace special:magic silent, initialClass:xwaylandvideobridge
# Calculator
windowrulev2 = workspace special:magic silent, initialClass:io.github.Qalculate.qalculate-qt
windowrulev2 = float, initialClass:io.github.Qalculate.qalculate-qt
windowrulev2 = size 600 400, initialClass:io.github.Qalculate.qalculate-qt
windowrulev2 = move 100 400, initialClass:io.github.Qalculate.qalculate-qt
# Nautilus
windowrulev2 = workspace 3, initialClass:org.gnome.Nautilus
# Onedrive
windowrulev2 = float, initialClass:OneDriveGUI
# Virtualbox
windowrulev2 = workspace 4, initialClass:VirtualBox Manager
windowrulev2 = workspace 8, initialClass:VirtualBox Machine
windowrulev2 = workspace special silent, initialClass:VirtualBoxVM
windowrulev2 = workspace special silent, initialClass:VirtualBox

# Chromium
windowrulev2 = workspace 20, class:chromium-browser
windowrulev2 = workspace 20, class:google-chrome
# Open Folder Dialog
windowrulev2 = float, initialClass:xdg-desktop-portal-gtk
windowrulev2 = size 800 600, initialClass:xdg-desktop-portal-gtk

# Zentiy Dialog
windowrulev2 = float, initialClass:zenity
windowrulev2 = size 300 300, initialClass:zenity
